version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn ows.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    build: 
      context: ../
      dockerfile: Dockerfile
    image: webapp:${branch}
    expose:
      - 8000
    env_file:
      - ../.env.prod

  nginx:
    build: ./nginx
    build: 
      context: ../
      dockerfile: docker/Dockerfile-nginx
    image: nginx:${branch}
    ports:
      - 80:80
    depends_on:
      - web      